---
image: docker:stable

services:
- docker:dind

.docker_login: &docker_login |
  echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

stages:
- lint-test
- build

lint:
  stage: lint-test
  image: node:8.16.1-alpine
  script:
  - yarn install
  - yarn run lint

test-unit:
  stage: lint-test
  image: node:8.16.1-alpine
  script:
  - yarn install
  - yarn run test:unit

# test-e2e:
#   stage: lint-test
#   image: cypress/base:12.6.0
#   script:
#   - yarn install
#   - yarn run test:e2e

build-master:
  stage: build
  script:
  - *docker_login
  - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  - docker push "$CI_REGISTRY_IMAGE"
  only:
    refs:
    - master

build:
  stage: build
  script:
  - *docker_login
  - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
  - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  except:
    refs:
    - master
